language: csharp
solution: ASPNetCoreAngular2YoExample.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - npm install
 - npm run webpack:deploy
 - dotnet build ./ASPNetCoreAngular2YoExample.csproj
 - npm test