language: csharp
solution: ASPNetCoreAngular2YoExample.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - npm install
 - node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod
 - node node_modules/webpack/bin/webpack.js --env.prod
 - dotnet restore
 - dotnet build