version: '2'

services:
  web:
    build: .
    image: aspnetcore-angular
    ports:
      - "80:41224"
    depends_on:
      - "db"
    command: ["bash", "./wait-for-postgres.sh", "db", "5432", "--", "dotnet", "run", "--launch-profile", "Docker"]
    environment:
      - PGUSER=docker
      - PGPASSWORD=docker
    volumes:
      - ${APPDATA}/microsoft/UserSecrets/:/root/.microsoft/usersecrets

  db:
    image: postgres
    container_name: pg-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
