version: '3'

services:
  aspnetcoreangular2yoexample:
    image: aspnetcoreangular2yoexample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${APPDATA}/microsoft/UserSecrets/:/root/.microsoft/usersecrets
      # To avoid the System.InvalidOperationException: The antiforgery token could not be decrypted
      - ${LOCALAPPDATA}\ASP.NET\DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
    environment:
      - PGUSER=docker
      - PGPASSWORD=docker

  db:
    image: postgres
    container_name: pg-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3